### ISSUE TITLE
Congratulations, but I have a problem.

### ISSUE THREAD

**Issue by m-peker** [chuzcjoe/crowd-tracking-and-visualizing-from-top-view#1]
Hi,

The pictures of your work are impressive. But there are missing functions (expand_pixel, distance, view_angle_pressure) in the utils file. Can you submit the full version of this file?

Thanks in advance.

**Comment by chuzcjoe** [comment]
> Hi,
> 
> The pictures of your work are impressive. But there are missing functions (expand_pixel, distance, view_angle_pressure) in the utils file. Can you submit the full version of this file?
> 
> Thanks in advance.

Thanks for mentioning that. I have re-uploaded everything. Let me know if you have any questions.

**Comment by m-peker** [comment]
Hi,

Thank you very much. 

Best Regards.

**Comment by m-peker** [comment]
Hi,

I want to use it in People Detection
But there are many points on a person. I want to reduce this to a single point. How can I do it ?

Best Regards.

**Comment by chuzcjoe** [comment]
> Hi,
> 
> I want to use it in People Detection
> But there are many points on a person. I want to reduce this to a single point. How can I do it ?
> 
> Best Regards.

Hi,

This approach only works for detecting moving objects from a far view where the human body contour is not visible like I showed in the image. Each person is actually a black dot from the top view. If you want to detect a person, if the person object can be clearly identified in the image, I would suggest you use some deep learning-based methods. It would be very helpful if you can post one of your sample images and I can help to check if this approach works.

**Comment by m-peker** [comment]
Hi,

Thank you for your suggestions. I got very good results with deep learning. But I need to develop a low-cost system. Your software is pretty good at this. In fact, it captures one's position well. But since there are many points, person detection becomes difficult. A sample image is attached.

![example](https://user-images.githubusercontent.com/17083899/78218637-cbd06400-74c6-11ea-832e-3557000c1c4e.png)

**Comment by chuzcjoe** [comment]
> Hi,
> 
> Thank you for your suggestions. I got very good results with deep learning. But I need to develop a low-cost system. Your software is pretty good at this. In fact, it captures one's position well. But since there are many points, person detection becomes difficult. A sample image is attached.
> 
> ![example](https://user-images.githubusercontent.com/17083899/78218637-cbd06400-74c6-11ea-832e-3557000c1c4e.png)

One possible way to achieve that is to change some of the parameters in opt.py:

feature_params = dict( maxCorners = 120,    
                       qualityLevel = 0.3, #default 0.3
                       minDistance = 15,  #default 3
                       blockSize = 3 )  #default 3

My suggestion is to increase the value of **minDistance** and decrease the value of **maxCorners**.

And one more thing, this algorithm works terribly once your camera moves around.

**Comment by m-peker** [comment]
Thank you very much for your suggestions. I think I will reach my goal with this code. If I get results, I will share with you.

Best Regards.

**Comment by chuzcjoe** [comment]
> Thank you very much for your suggestions. I think I will reach my goal with this code. If I get results, I will share with you.
> 
> Best Regards.

Look forward to it.

Good luck!
